[package]
name = "hello-wasm"
version = "0.1.0"
edition = "2021"
description = "A smaple project with wasm-pack"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
